services:
  - type: web
    name: flipkart-clone
    runtime: docker
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO
    plan: free
    envVars:
      - key: DB_HOST
        value: mysql-198ea7f5-atickoo1-b6c3.i.aivencloud.com
      - key: DB_NAME
        value: ecommerce_db
      - key: DB_USER
        value: avnadmin
      - key: DB_PASS
        sync: false
